# This is a basic workflow to help you get started with Actions
name: Output context

# Event triggers
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step will output the context and env variables available to the workflow
      - name: Show context
        uses: actions/github-script@v4
        with:
          script: |            
            core.startGroup('Context');
            core.info(JSON.stringify(context, null, 2))
            core.endGroup();
            
            core.startGroup('Env Vars');
            core.info(JSON.stringify(process.env, null, 2));
            core.endGroup();
      
      # This step checks out the workflow repository so that the runner can access the content
      - name: Checkout
        uses: actions/checkout@v2
        
      # This step runs a shell command on the runner machine
      - name: Run a shell command
        run: echo "Hello world"
    
